sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master


php:
  - 7.4snapshot
  - 7.3
  - 7.2
  - 7.1

env:
  - WP_VERSION=4.9 WP_MULTISITE=1
  - WP_VERSION=4.9 WP_MULTISITE=0