sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master


php:
  - 7.4snapshot
  - 7.3
  - 7.2
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.1 WP_MULTISITE=1
  - WP_VERSION=5.1 WP_MULTISITE=0
  - WP_VERSION=5.0 WP_MULTISITE=1
  - WP_VERSION=5.0 WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=1
  - WP_VERSION=4.9 WP_MULTISITE=0


script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit --exclude-group multisite
      WP_MULTISITE=1 phpunit --exclude-group singlesite
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
